# Ce fichier est le point d'entrée pour configurer vos propres services.
# Les fichiers dans le sous-répertoire packages/ configurent vos dépendances.

# Mettez ici les paramètres qui n'ont pas besoin de changer sur chaque machine où l'application est déployée.
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # configuration par défaut pour les services dans *ce* fichier
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services.
        autoconfigure: true # Enregistre automatiquement vos services comme commandes, abonnés aux événements, etc.

    # rend les classes dans src/ disponibles pour être utilisées comme services
    # ceci crée un service par classe dont l'id est le nom complet de la classe
    App\:
        resource: '../src/' # Charge les services depuis le répertoire src/
        exclude:
            - '../src/DependencyInjection/' # Exclut le répertoire DependencyInjection/
            - '../src/Entity/' # Exclut le répertoire Entity/
            - '../src/Kernel.php' # Exclut le fichier Kernel.php

    # Définir le service HttpClient pour l'API Nominatim
    # Ceci configure le service ApiHttpClient pour utiliser le client HTTP nommé 'jph',
    # que nous avons configuré pour interagir avec l'API Nominatim.
    App\HttpClient\ApiHttpClient:
        arguments:
            $httpClient: '@http_client' # Injecte le client HTTP 'jph' dans le service ApiHttpClient

    # Assure que ApiController a la bonne dépendance injectée
    # Ceci configure le contrôleur ApiController pour recevoir une instance de ApiHttpClient.
    App\Controller\ApiController:
        arguments:
            $apiHttpClient: '@App\HttpClient\ApiHttpClient' # Injecte le service ApiHttpClient dans le contrôleur ApiController

    # ajoutez plus de définitions de services lorsque la configuration explicite est nécessaire
    # notez que les dernières définitions remplacent toujours les précédentes
